### Запрос токенов
POST http://localhost:5000/amo-crm/tokens HTTP/1.1
Content-Type: application/json

{
  "client_id": "6e2d7705-a5e6-4df0-b9c1-26c74469df02",
  "client_secret": "XzT4ZWBzjMQD33zp0d98xUqGLfBl1YgYZ1V6D8gJ35I47nw72RKvHLczIBZ1ZJxy",
  "grant_type": "authorization_code",
  "code": "def50200eda36cb877a84b7e301fc36922fdf635b23503469006b3f478157aa41a30cdbadb8f0122a21098dfda7ea06fe740745a95f1984b8939a8c3476348d3491f7af874bf52f3d3695376ae7d6d08ac6b16cb2f02a48f5e4781fdde3392c65c718f83135350fe4d9db75777b93713f32d79eb51a3b78bb2e0210818c70e1f6e494201070b6bbf979a52071bfa227d6a8a50b237da6a10047910d8cf14e06bc27d29e3cc272f8b7d50a8087687ddf6ffc52b6127655550aa54a6f359cffa045a6634ad1ff89a9f2eb4963202b5c3b4edaeaadf5538cff5e4469dcc9851b34d4bf2b57c604c54e5218efc001c03017a2e2bcb16c09d5ec1f81e8ff662ce6880e96e3189c0db848050bc6937d6daff8f02b87e5cb644305ce58fbded3c4a15369b7630883ae2e10236c663ab1a243ecf08147ba8ee0fca467b5401fc863aa75b0a1cb970cc906df1b78d5a0fa46e3986afbc17171a876389500d456230a77bb2b5431894e68adb251edd7c8e86401b47ca2af0b5498a383c2b4d2f5184f0dacb412b7316bd74ee0a4d1d61d8ada21a646f0ba81580d62d141659edeadd58ef6a5955662549c11e0bdf3ab01cdeba06d79092e7ec734dac77e7b190fbf0278b62e98615c1dda592f7f5f2877ba36698a4533e6270e3a4a9fa383ec350fd0c07234b72",
  "redirect_uri": "https://localhost"
}

### Запрос списка контактов
GET http://localhost:5000/amo-crm/contacts?query=89105550005 HTTP/1.1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImp0aSI6ImQxYTQ0OGExNDViODM0NmQzZWFiNGVjZWEzYjMxOWNjNWRjOTU1OGIwZTA2NzU2NjczMGNlZjkyMWNjY2IyMjQyNDc1MWEyYTBkMmJmMWMwIn0.eyJhdWQiOiI2ZTJkNzcwNS1hNWU2LTRkZjAtYjljMS0yNmM3NDQ2OWRmMDIiLCJqdGkiOiJkMWE0NDhhMTQ1YjgzNDZkM2VhYjRlY2VhM2IzMTljYzVkYzk1NThiMGUwNjc1NjY3MzBjZWY5MjFjY2NiMjI0MjQ3NTFhMmEwZDJiZjFjMCIsImlhdCI6MTcwMDU3NDM0NCwibmJmIjoxNzAwNTc0MzQ0LCJleHAiOjE3MDA2NjA3NDQsInN1YiI6IjEwMzYwMzY2IiwiZ3JhbnRfdHlwZSI6IiIsImFjY291bnRfaWQiOjMxNDE2ODU0LCJiYXNlX2RvbWFpbiI6ImFtb2NybS5ydSIsInZlcnNpb24iOjIsInNjb3BlcyI6WyJwdXNoX25vdGlmaWNhdGlvbnMiLCJmaWxlcyIsImNybSIsImZpbGVzX2RlbGV0ZSIsIm5vdGlmaWNhdGlvbnMiXX0.SxXeT9lx3OApKwuqiMI-C5ljP_O8WWRf5x1dCmt-T2KKsQmlJjXv7H5bymvyISUmUK1xdUF-aHwk-9uO6WvMTOEFaokjy7yQht6A6-gnKDO-gt2ZYOfwjLiOL6Qg-g1DZI0YGfQoC2LRIV3w66-ze4KkvwX2FjnnPEGnItc6M0CNxTZ0mq1INexncNmgbWy65Wa1Sq7BWrvz6-sMqU-JPDSiwjoigEw65MT9hoDaBpT_bRUkkgVJu_tRg41oipSX1ShEdYDKisF2UFCJhgF4ibsPlyJoqFlHIQxwemwxgQzRmLziNcV5apwQ7QfsXCQWy2b1j5eeQQduvCi7P5mfGA

### Добавление контакта
POST http://localhost:5000/amo-crm/contacts HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImp0aSI6ImQxYTQ0OGExNDViODM0NmQzZWFiNGVjZWEzYjMxOWNjNWRjOTU1OGIwZTA2NzU2NjczMGNlZjkyMWNjY2IyMjQyNDc1MWEyYTBkMmJmMWMwIn0.eyJhdWQiOiI2ZTJkNzcwNS1hNWU2LTRkZjAtYjljMS0yNmM3NDQ2OWRmMDIiLCJqdGkiOiJkMWE0NDhhMTQ1YjgzNDZkM2VhYjRlY2VhM2IzMTljYzVkYzk1NThiMGUwNjc1NjY3MzBjZWY5MjFjY2NiMjI0MjQ3NTFhMmEwZDJiZjFjMCIsImlhdCI6MTcwMDU3NDM0NCwibmJmIjoxNzAwNTc0MzQ0LCJleHAiOjE3MDA2NjA3NDQsInN1YiI6IjEwMzYwMzY2IiwiZ3JhbnRfdHlwZSI6IiIsImFjY291bnRfaWQiOjMxNDE2ODU0LCJiYXNlX2RvbWFpbiI6ImFtb2NybS5ydSIsInZlcnNpb24iOjIsInNjb3BlcyI6WyJwdXNoX25vdGlmaWNhdGlvbnMiLCJmaWxlcyIsImNybSIsImZpbGVzX2RlbGV0ZSIsIm5vdGlmaWNhdGlvbnMiXX0.SxXeT9lx3OApKwuqiMI-C5ljP_O8WWRf5x1dCmt-T2KKsQmlJjXv7H5bymvyISUmUK1xdUF-aHwk-9uO6WvMTOEFaokjy7yQht6A6-gnKDO-gt2ZYOfwjLiOL6Qg-g1DZI0YGfQoC2LRIV3w66-ze4KkvwX2FjnnPEGnItc6M0CNxTZ0mq1INexncNmgbWy65Wa1Sq7BWrvz6-sMqU-JPDSiwjoigEw65MT9hoDaBpT_bRUkkgVJu_tRg41oipSX1ShEdYDKisF2UFCJhgF4ibsPlyJoqFlHIQxwemwxgQzRmLziNcV5apwQ7QfsXCQWy2b1j5eeQQduvCi7P5mfGA

[
  {
    "first_name": "Михаил",
    "last_name": "Сахаров",
    "custom_fields_values": [
      {
        "field_id": 1451443,
        "values": [
          {
            "value": "89996136622"
          }
        ]
      },
      {
        "field_id": 1451445,
        "values": [
          {
            "value": "sakharov_mikhail@hotmail.com"
          }
        ]
      }
    ]
  },
  {
    "name": "Михаил Сахаров"
  },
  {
    "company": "DotSales"
  }
]

### Редактирование контакта
PATCH http://localhost:5000/amo-crm/contacts HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImp0aSI6ImQxYTQ0OGExNDViODM0NmQzZWFiNGVjZWEzYjMxOWNjNWRjOTU1OGIwZTA2NzU2NjczMGNlZjkyMWNjY2IyMjQyNDc1MWEyYTBkMmJmMWMwIn0.eyJhdWQiOiI2ZTJkNzcwNS1hNWU2LTRkZjAtYjljMS0yNmM3NDQ2OWRmMDIiLCJqdGkiOiJkMWE0NDhhMTQ1YjgzNDZkM2VhYjRlY2VhM2IzMTljYzVkYzk1NThiMGUwNjc1NjY3MzBjZWY5MjFjY2NiMjI0MjQ3NTFhMmEwZDJiZjFjMCIsImlhdCI6MTcwMDU3NDM0NCwibmJmIjoxNzAwNTc0MzQ0LCJleHAiOjE3MDA2NjA3NDQsInN1YiI6IjEwMzYwMzY2IiwiZ3JhbnRfdHlwZSI6IiIsImFjY291bnRfaWQiOjMxNDE2ODU0LCJiYXNlX2RvbWFpbiI6ImFtb2NybS5ydSIsInZlcnNpb24iOjIsInNjb3BlcyI6WyJwdXNoX25vdGlmaWNhdGlvbnMiLCJmaWxlcyIsImNybSIsImZpbGVzX2RlbGV0ZSIsIm5vdGlmaWNhdGlvbnMiXX0.SxXeT9lx3OApKwuqiMI-C5ljP_O8WWRf5x1dCmt-T2KKsQmlJjXv7H5bymvyISUmUK1xdUF-aHwk-9uO6WvMTOEFaokjy7yQht6A6-gnKDO-gt2ZYOfwjLiOL6Qg-g1DZI0YGfQoC2LRIV3w66-ze4KkvwX2FjnnPEGnItc6M0CNxTZ0mq1INexncNmgbWy65Wa1Sq7BWrvz6-sMqU-JPDSiwjoigEw65MT9hoDaBpT_bRUkkgVJu_tRg41oipSX1ShEdYDKisF2UFCJhgF4ibsPlyJoqFlHIQxwemwxgQzRmLziNcV5apwQ7QfsXCQWy2b1j5eeQQduvCi7P5mfGA

[
  {
    "id": 13238585,
    "first_name": "Петр",
    "last_name": "Смирнов",
    "custom_fields_values": [
      {
        "field_id": 1451443,
        "field_name": "Телефон",
        "values": [
          {
            "value": "89105550005"
          }
        ]
      },
      {
        "field_id": 1451445,
        "field_name": "Email",
        "values": [
          {
            "value": "petr_first@mail.ru"
          }
        ]
      }
    ]
  }
]
